# Generated by Django 6.0.2 on 2026-04-05 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.CharField(db_collation='Thai_CS_AI', max_length=6, primary_key=True, serialize=False)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'recipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.CharField(db_collation='Thai_CS_AI', max_length=6, primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_collation='Thai_CS_AI', max_length=100)),
            ],
            options={
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(db_collation='Thai_CS_AI', max_length=6, primary_key=True, serialize=False)),
                ('cus_name', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=100, null=True)),
                ('cus_phone', models.CharField(db_collation='Thai_CS_AI', max_length=20, unique=True)),
                ('cus_email', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=100, null=True)),
                ('member_points', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.CharField(db_collation='Thai_CS_AI', max_length=6, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(db_collation='Thai_CS_AI', max_length=100)),
                ('position', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=100, null=True)),
                ('emp_phone', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=50, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emp_status', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=50, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.CharField(db_collation='Thai_CS_AI', max_length=6, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(db_collation='Thai_CS_AI', max_length=150)),
                ('contact_name', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=255, null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(db_collation='Thai_CS_AI', max_length=6, primary_key=True, serialize=False)),
                ('order_datetime', models.DateTimeField(blank=True, null=True)),
                ('order_type', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=20, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.customers')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.employees')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_datetime', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=50, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=20, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.orders')),
            ],
            options={
                'db_table': 'payments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(db_collation='Thai_CS_AI', max_length=6, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_collation='Thai_CS_AI', max_length=150)),
                ('description', models.TextField(blank=True, db_collation='Thai_CS_AI', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=50, null=True)),
                ('is_active', models.CharField(db_collation='Thai_CS_AI', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.categories')),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('note', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=255, null=True)),
                ('sweetness', models.IntegerField(blank=True, default=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.products')),
            ],
            options={
                'db_table': 'order_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_id', models.CharField(db_collation='Thai_CS_AI', max_length=6, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(db_collation='Thai_CS_AI', max_length=150)),
                ('unit', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=50, null=True)),
                ('stock_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('ingredirent_status', models.CharField(blank=True, db_collation='Thai_CS_AI', max_length=20, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.suppliers')),
            ],
            options={
                'db_table': 'ingredients',
                'managed': True,
            },
        ),
    ]
