# Generated by Django 6.0.2 on 2026-04-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='sweetness',
        ),
    ]
