# Generated by Django 6.0.2 on 2026-04-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_orderdetails_sweetness'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='sweetness',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
