# Generated by Django 6.0.2 on 2026-04-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orderdetails_sweetness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='ingredients',
            name='classifier',
            field=models.CharField(blank=True, choices=[('กล่อง', 'กล่อง'), ('ขวด', 'ขวด'), ('ห่อ', 'ห่อ'), ('ชิ้น', 'ชิ้น'), ('ถุง', 'ถุง')], db_collation='Thai_CS_AI', default='ชิ้น', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='unit_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Assistant manager', 'Assistant manager'), ('Sales', 'Sales')], db_collation='Thai_CS_AI', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(blank=True, choices=[('กรัม', 'กรัม (g)'), ('มิลลิลิตร', 'มิลลิลิตร (ml)'), ('ชิ้น', 'ชิ้น (pcs)'), ('Topping', 'Topping')], db_collation='Thai_CS_AI', max_length=50, null=True),
        ),
    ]
